### ISSUE TITLE
Déployer une instance de Grav pour le club Avion Cargo

### ISSUE THREAD

**Issue by SonOfLope** [ClubCedille/Plateforme-Cedille#48]
### Description

Déployer une instance du CMS Grav pour leclub étudiant AvionCargo. Ce site sera d'abord en développement et devra donc utiliser notre domaine interne *.cedille.club. Ce déploiement sera le nouveau standard pour héberger les sites web des clubs étudiants, il est donc impératif que la mise en œuvre soit facile à comprendre et réutilisable. 

### Expected behavior

Le déploiement de l'instance Grav doit :

- Fournir un environnement de développement stable sous le domaine *.cedille.club.
- Assurer une transition facile de l'environnement de développement à la production.
- Utiliser des processus de déploiement documentés pour permettre une réutilisation facile pour de futurs sites de clubs étudiants.

### Milestones

- [ ] Obtenir le thème choisi par le club Avion Cargo
- [ ] Configuration du domaine interne et du système DNS pour nomduclub.cedille.club.
- [ ] Préparation des conteneurs Docker pour Grav pour une portabilité et une réutilisation maximales (à partir du repertoire cedille-dockerfiles).
- [ ] Création d'un pipeline de déploiement automatisé (à partir du repertoire cedille-dockerfiles).
- [ ] Documentation du processus de déploiement et des configurations utilisées.

### Completion criteria

L'instance Grav est accessible via nomduclub.cedille.club et fonctionne sans erreur.
La documentation est complète et permet à un développeur de répliquer le déploiement pour un autre club étudiant.
Les scripts de déploiement automatisés fonctionnent sans intervention manuelle.
Le passage de l'environnement de développement à la production est bien compris et documenté.

### Related tasks

na

### Additionnal information

Documentation officielle de Grav : [Grav Documentation](https://learn.getgrav.org/)
