### ISSUE TITLE
Regarder pour l'installation/configuration de Clickhouse Keeper

### ISSUE THREAD

**Issue by ThomasCardin** [ClubCedille/Plateforme-Cedille#71]
### Description

ClickHouse Keeper remplace ZooKeeper pour gérer la cohérence des données dans les clusters ClickHouse. Il réduit la complexité en éliminant le besoin de services tiers et améliore les performances en étant spécialement conçu pour ClickHouse, offrant ainsi une solution de coordination plus efficace et robuste pour les bases de données distribuées.

### Expected behavior

Meme comportement que ZooKeeper, mais avec une meilleur intégration pour Clickhouse

### Milestones

- [ ] Comporendre le fonctionnement
- [ ] Prendre une décision sur l'installation
- [ ] L'installer s'il y a lieu
